# MySQL Configuration
mysql:
    host: "127.0.0.1"
    port: 3306
    database: "minecraft"
    username: "user"
    password: "password"
    append: "?useSSL=false"

# Redis Configuration
redis:
    host: "127.0.0.1"
    port: 6379
    timeout: 10000
    password: ""
    database: 0