name: Java CI - Build

on:
  pull_request:
    branches:
      - master
      - Spigot-*
  push:
    branches:
      - master
      - Spigot-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn -B package --file pom.xml
